# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.setEnabled(True)
        Form.setFixedSize(970, 576)
        Form.setMaximumSize(QtCore.QSize(970, 576))
        Form.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Free_Sample_By_Wix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.India))
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(-130, -20, 1111, 611))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/abstract_background_with_grunge_brush_stroke_and_black_border_1401.png);")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(790, 550, 171, 20))
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(350, 30, 281, 481))
        self.frame.setStyleSheet("background-image: url(:/newPrefix/Qr.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget_register = QtWidgets.QWidget(Form)
        self.widget_register.setGeometry(QtCore.QRect(350, 30, 281, 481))
        self.widget_register.setObjectName("widget_register")
        self.s_register = QtWidgets.QPushButton(self.widget_register)
        self.s_register.setGeometry(QtCore.QRect(10, 420, 261, 41))
        self.s_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s_register.setMouseTracking(True)
        self.s_register.setToolTip("")
        self.s_register.setStyleSheet("QPushButton#s_register{\n"
"border-radius:20px;\n"
"font: 20pt \"Arial Unicode MS\";\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#s_register:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.s_register.setObjectName("s_register")
        self.label_8 = QtWidgets.QLabel(self.widget_register)
        self.label_8.setGeometry(QtCore.QRect(0, 30, 281, 51))
        self.label_8.setStyleSheet("color: rgb(223, 129, 129);")
        self.label_8.setObjectName("label_8")
        self.s_email = QtWidgets.QLineEdit(self.widget_register)
        self.s_email.setGeometry(QtCore.QRect(10, 180, 261, 31))
        self.s_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.s_email.setObjectName("s_email")
        self.label_9 = QtWidgets.QLabel(self.widget_register)
        self.label_9.setGeometry(QtCore.QRect(10, 280, 101, 30))
        self.label_9.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget_register)
        self.label_10.setGeometry(QtCore.QRect(10, 340, 161, 30))
        self.label_10.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_10.setObjectName("label_10")
        self.s_password = QtWidgets.QLineEdit(self.widget_register)
        self.s_password.setGeometry(QtCore.QRect(10, 310, 261, 31))
        self.s_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.s_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.s_password.setObjectName("s_password")
        self.label_11 = QtWidgets.QLabel(self.widget_register)
        self.label_11.setGeometry(QtCore.QRect(10, 150, 61, 21))
        self.label_11.setStyleSheet("font: 700 20pt \"Segoe Print\";\n"
"color: rgb(220, 127, 127);")
        self.label_11.setObjectName("label_11")
        self.s_confirm_password = QtWidgets.QLineEdit(self.widget_register)
        self.s_confirm_password.setGeometry(QtCore.QRect(10, 370, 261, 31))
        self.s_confirm_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.s_confirm_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.s_confirm_password.setObjectName("s_confirm_password")
        self.s_back = QtWidgets.QPushButton(self.widget_register)
        self.s_back.setGeometry(QtCore.QRect(0, 0, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.s_back.setFont(font)
        self.s_back.setStyleSheet("QPushButton#s_back{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"}\n"
"QPushButton#s_back:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#s_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.s_back.setObjectName("s_back")
        self.widget_login = QtWidgets.QWidget(Form)
        self.widget_login.setGeometry(QtCore.QRect(350, 30, 281, 481))
        self.widget_login.setObjectName("widget_login")
        self.l_password = QtWidgets.QLineEdit(self.widget_login)
        self.l_password.setGeometry(QtCore.QRect(10, 310, 261, 31))
        self.l_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.l_password.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.l_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.l_password.setClearButtonEnabled(True)
        self.l_password.setObjectName("l_password")
        self.label_5 = QtWidgets.QLabel(self.widget_login)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 61, 21))
        self.label_5.setStyleSheet("font: 700 20pt \"Segoe Print\";\n"
"color: rgb(220, 127, 127);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_login)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 101, 31))
        self.label_6.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_6.setObjectName("label_6")
        self.l_forget = QtWidgets.QPushButton(self.widget_login)
        self.l_forget.setGeometry(QtCore.QRect(10, 420, 261, 41))
        self.l_forget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l_forget.setMouseTracking(True)
        self.l_forget.setToolTip("")
        self.l_forget.setStyleSheet("QPushButton#l_forget{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"border-radius:20px;\n"
"font: 20pt \"Arial Unicode MS\";\n"
"}\n"
"QPushButton#l_forget:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.l_forget.setObjectName("l_forget")
        self.l_login = QtWidgets.QPushButton(self.widget_login)
        self.l_login.setGeometry(QtCore.QRect(10, 360, 261, 41))
        self.l_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.l_login.setMouseTracking(True)
        self.l_login.setToolTip("")
        self.l_login.setStyleSheet("QPushButton#l_login{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"border-radius:20px;\n"
"font: 20pt \"Arial Unicode MS\";\n"
"}\n"
"QPushButton#l_login:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.l_login.setObjectName("l_login")
        self.l_email = QtWidgets.QLineEdit(self.widget_login)
        self.l_email.setGeometry(QtCore.QRect(10, 180, 261, 31))
        self.l_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.l_email.setInputMethodHints(QtCore.Qt.ImhNone)
        self.l_email.setClearButtonEnabled(True)
        self.l_email.setObjectName("l_email")
        self.label_7 = QtWidgets.QLabel(self.widget_login)
        self.label_7.setGeometry(QtCore.QRect(0, 30, 281, 51))
        self.label_7.setStyleSheet("color: rgb(223, 129, 129);")
        self.label_7.setObjectName("label_7")
        self.l_back = QtWidgets.QPushButton(self.widget_login)
        self.l_back.setGeometry(QtCore.QRect(0, 0, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.l_back.setFont(font)
        self.l_back.setStyleSheet("QPushButton#l_back{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"}\n"
"QPushButton#l_back:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#l_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.l_back.setObjectName("l_back")
        self.widget_forget = QtWidgets.QWidget(Form)
        self.widget_forget.setGeometry(QtCore.QRect(350, 30, 281, 481))
        self.widget_forget.setObjectName("widget_forget")
        self.f_otp = QtWidgets.QLineEdit(self.widget_forget)
        self.f_otp.setGeometry(QtCore.QRect(10, 180, 261, 31))
        self.f_otp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.f_otp.setInputMethodHints(QtCore.Qt.ImhNone)
        self.f_otp.setClearButtonEnabled(True)
        self.f_otp.setObjectName("f_otp")
        self.label_12 = QtWidgets.QLabel(self.widget_forget)
        self.label_12.setGeometry(QtCore.QRect(0, 30, 281, 51))
        self.label_12.setStyleSheet("color: rgb(223, 129, 129);")
        self.label_12.setObjectName("label_12")
        self.f_resend = QtWidgets.QPushButton(self.widget_forget)
        self.f_resend.setGeometry(QtCore.QRect(10, 420, 261, 41))
        self.f_resend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f_resend.setMouseTracking(True)
        self.f_resend.setToolTip("")
        self.f_resend.setStyleSheet("QPushButton#f_resend{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"border-radius:20px;\n"
"font: 20pt \"Arial Unicode MS\";\n"
"}\n"
"QPushButton#f_resend:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.f_resend.setObjectName("f_resend")
        self.f_submit = QtWidgets.QPushButton(self.widget_forget)
        self.f_submit.setGeometry(QtCore.QRect(10, 330, 261, 41))
        self.f_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f_submit.setMouseTracking(True)
        self.f_submit.setToolTip("")
        self.f_submit.setStyleSheet("QPushButton#f_submit{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"border-radius:20px;\n"
"font: 20pt \"Arial Unicode MS\";\n"
"}\n"
"QPushButton#f_submit:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.f_submit.setObjectName("f_submit")
        self.label_13 = QtWidgets.QLabel(self.widget_forget)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 61, 21))
        self.label_13.setStyleSheet("font: 700 20pt \"Segoe Print\";\n"
"color: rgb(220, 127, 127);")
        self.label_13.setObjectName("label_13")
        self.f_back = QtWidgets.QPushButton(self.widget_forget)
        self.f_back.setGeometry(QtCore.QRect(0, 0, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.f_back.setFont(font)
        self.f_back.setStyleSheet("QPushButton#f_back{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"}\n"
"QPushButton#f_back:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#f_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.f_back.setObjectName("f_back")
        self.widget_welcome = QtWidgets.QWidget(Form)
        self.widget_welcome.setGeometry(QtCore.QRect(350, 30, 281, 481))
        self.widget_welcome.setObjectName("widget_welcome")
        self.label = QtWidgets.QLabel(self.widget_welcome)
        self.label.setGeometry(QtCore.QRect(0, 30, 281, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.w_login = QtWidgets.QPushButton(self.widget_welcome)
        self.w_login.setGeometry(QtCore.QRect(10, 320, 261, 41))
        self.w_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.w_login.setMouseTracking(True)
        self.w_login.setToolTip("")
        self.w_login.setStyleSheet("QPushButton#w_login{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"border-radius:20px;\n"
"font: 20pt \"Arial Unicode MS\";\n"
"}\n"
"QPushButton#w_login:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.w_login.setObjectName("w_login")
        self.label_2 = QtWidgets.QLabel(self.widget_welcome)
        self.label_2.setGeometry(QtCore.QRect(0, 140, 281, 31))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.551, x2:0, y2:0.545455, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.label_2.setObjectName("label_2")
        self.w_register = QtWidgets.QPushButton(self.widget_welcome)
        self.w_register.setGeometry(QtCore.QRect(10, 400, 261, 41))
        self.w_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.w_register.setMouseTracking(True)
        self.w_register.setToolTip("")
        self.w_register.setStyleSheet("QPushButton#w_register{\n"
"border-radius:20px;\n"
"font: 14pt \"Arial Unicode MS\";\n"
"background-color: qlineargradient(spread:pad, x1:0.506, y1:0.0227273, x2:0.472, y2:0.977273, stop:0 rgba(0, 167, 175, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton#w_register:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.w_register.setObjectName("w_register")
        self.widget_register_details = QtWidgets.QWidget(Form)
        self.widget_register_details.setGeometry(QtCore.QRect(160, 150, 671, 341))
        self.widget_register_details.setObjectName("widget_register_details")
        self.label_16 = QtWidgets.QLabel(self.widget_register_details)
        self.label_16.setGeometry(QtCore.QRect(190, 0, 221, 41))
        self.label_16.setStyleSheet("color: rgb(222, 128, 128);")
        self.label_16.setObjectName("label_16")
        self.r_register = QtWidgets.QPushButton(self.widget_register_details)
        self.r_register.setGeometry(QtCore.QRect(200, 290, 261, 41))
        self.r_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.r_register.setMouseTracking(True)
        self.r_register.setToolTip("")
        self.r_register.setStyleSheet("QPushButton#r_register{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"border-radius:20px;\n"
"font: 20pt \"Arial Unicode MS\";\n"
"}\n"
"QPushButton#r_register:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.r_register.setFlat(False)
        self.r_register.setObjectName("r_register")
        self.r_last_name = QtWidgets.QLineEdit(self.widget_register_details)
        self.r_last_name.setGeometry(QtCore.QRect(390, 70, 271, 31))
        self.r_last_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.r_last_name.setObjectName("r_last_name")
        self.label_17 = QtWidgets.QLabel(self.widget_register_details)
        self.label_17.setGeometry(QtCore.QRect(390, 40, 101, 30))
        self.label_17.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget_register_details)
        self.label_18.setGeometry(QtCore.QRect(-10, 40, 101, 31))
        self.label_18.setStyleSheet("font: 700 20pt \"Segoe Print\";\n"
"color: rgb(220, 127, 127);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_register_details)
        self.label_19.setGeometry(QtCore.QRect(390, 220, 101, 30))
        self.label_19.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_19.setObjectName("label_19")
        self.r_password = QtWidgets.QLineEdit(self.widget_register_details)
        self.r_password.setGeometry(QtCore.QRect(390, 250, 271, 31))
        self.r_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.r_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.r_password.setReadOnly(True)
        self.r_password.setObjectName("r_password")
        self.r_upi = QtWidgets.QLineEdit(self.widget_register_details)
        self.r_upi.setGeometry(QtCore.QRect(390, 130, 271, 31))
        self.r_upi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.r_upi.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.r_upi.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.r_upi.setReadOnly(False)
        self.r_upi.setObjectName("r_upi")
        self.r_answer = QtWidgets.QLineEdit(self.widget_register_details)
        self.r_answer.setGeometry(QtCore.QRect(390, 190, 271, 31))
        self.r_answer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.r_answer.setObjectName("r_answer")
        self.r_comboBox = QtWidgets.QComboBox(self.widget_register_details)
        self.r_comboBox.setGeometry(QtCore.QRect(10, 190, 271, 31))
        self.r_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.r_comboBox.setObjectName("r_comboBox")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.r_comboBox.addItem("")
        self.r_email = QtWidgets.QLineEdit(self.widget_register_details)
        self.r_email.setGeometry(QtCore.QRect(10, 250, 271, 31))
        self.r_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.r_email.setReadOnly(True)
        self.r_email.setObjectName("r_email")
        self.r_first_name = QtWidgets.QLineEdit(self.widget_register_details)
        self.r_first_name.setGeometry(QtCore.QRect(10, 70, 271, 31))
        self.r_first_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.r_first_name.setObjectName("r_first_name")
        self.label_20 = QtWidgets.QLabel(self.widget_register_details)
        self.label_20.setGeometry(QtCore.QRect(10, 100, 141, 30))
        self.label_20.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_register_details)
        self.label_21.setGeometry(QtCore.QRect(390, 100, 81, 30))
        self.label_21.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_register_details)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 151, 31))
        self.label_22.setStyleSheet("font: 700 20pt \"Segoe Print\";\n"
"color: rgb(220, 127, 127);")
        self.label_22.setObjectName("label_22")
        self.r_phone_number = QtWidgets.QLineEdit(self.widget_register_details)
        self.r_phone_number.setGeometry(QtCore.QRect(10, 130, 271, 31))
        self.r_phone_number.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);")
        self.r_phone_number.setObjectName("r_phone_number")
        self.label_23 = QtWidgets.QLabel(self.widget_register_details)
        self.label_23.setGeometry(QtCore.QRect(10, 220, 71, 30))
        self.label_23.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_register_details)
        self.label_24.setGeometry(QtCore.QRect(390, 160, 81, 30))
        self.label_24.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 20pt \"Segoe Print\";")
        self.label_24.setObjectName("label_24")
        self.r_back = QtWidgets.QPushButton(self.widget_register_details)
        self.r_back.setGeometry(QtCore.QRect(0, 0, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.r_back.setFont(font)
        self.r_back.setStyleSheet("QPushButton#r_back{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 131, 120, 219), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,210);\n"
"border-top-right-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"}\n"
"QPushButton#r_back:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#r_back:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.r_back.setObjectName("r_back")
        self.widget_qrpay = QtWidgets.QWidget(Form)
        self.widget_qrpay.setGeometry(QtCore.QRect(10, 10, 951, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_qrpay.sizePolicy().hasHeightForWidth())
        self.widget_qrpay.setSizePolicy(sizePolicy)
        self.widget_qrpay.setObjectName("widget_qrpay")
        self.q_label = QtWidgets.QLabel(self.widget_qrpay)
        self.q_label.setGeometry(QtCore.QRect(50, 0, 851, 51))
        self.q_label.setStyleSheet("background-color: rgb(5, 50, 70);\n"
"font: 28pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.q_label.setObjectName("q_label")
        self.q_acc_ount = QtWidgets.QPushButton(self.widget_qrpay)
        self.q_acc_ount.setGeometry(QtCore.QRect(830, 60, 75, 24))
        self.q_acc_ount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_acc_ount.setStyleSheet("QPushButton#q_acc_ount{\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#q_acc_ount:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.q_acc_ount.setObjectName("q_acc_ount")
        self.q_log_out = QtWidgets.QPushButton(self.widget_qrpay)
        self.q_log_out.setGeometry(QtCore.QRect(760, 60, 61, 24))
        self.q_log_out.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_log_out.setStyleSheet("QPushButton#q_log_out{\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#q_log_out:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.q_log_out.setObjectName("q_log_out")
        self.q_old_details = QtWidgets.QPushButton(self.widget_qrpay)
        self.q_old_details.setGeometry(QtCore.QRect(50, 60, 75, 24))
        self.q_old_details.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_old_details.setStyleSheet("QPushButton#q_old_details{\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#q_old_details:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.q_old_details.setObjectName("q_old_details")
        self.line = QtWidgets.QFrame(self.widget_qrpay)
        self.line.setGeometry(QtCore.QRect(10, 80, 931, 20))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.widget_qrpay)
        self.line_2.setGeometry(QtCore.QRect(10, 90, 931, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.q_customer_name = QtWidgets.QLineEdit(self.widget_qrpay)
        self.q_customer_name.setGeometry(QtCore.QRect(20, 110, 181, 22))
        self.q_customer_name.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.q_customer_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.q_customer_name.setClearButtonEnabled(True)
        self.q_customer_name.setObjectName("q_customer_name")
        self.q_amount = QtWidgets.QLineEdit(self.widget_qrpay)
        self.q_amount.setGeometry(QtCore.QRect(360, 110, 91, 22))
        self.q_amount.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.q_amount.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.q_amount.setText("")
        self.q_amount.setReadOnly(True)
        self.q_amount.setObjectName("q_amount")
        self.q_customer_Phone = QtWidgets.QLineEdit(self.widget_qrpay)
        self.q_customer_Phone.setGeometry(QtCore.QRect(210, 110, 141, 22))
        self.q_customer_Phone.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.q_customer_Phone.setInputMask("")
        self.q_customer_Phone.setText("")
        self.q_customer_Phone.setClearButtonEnabled(True)
        self.q_customer_Phone.setObjectName("q_customer_Phone")
        self.q_upi = QtWidgets.QLineEdit(self.widget_qrpay)
        self.q_upi.setGeometry(QtCore.QRect(380, 60, 161, 22))
        self.q_upi.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.q_upi.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.q_upi.setAlignment(QtCore.Qt.AlignCenter)
        self.q_upi.setReadOnly(True)
        self.q_upi.setClearButtonEnabled(False)
        self.q_upi.setObjectName("q_upi")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget_qrpay)
        self.dateTimeEdit.setGeometry(QtCore.QRect(250, 60, 121, 22))
        self.dateTimeEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateTimeEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.India))
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime.currentDateTime())
        #self.dateTimeEdit.setTimeSpec(QtCore.Qt..LocalTime)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.q_qr_generate = QtWidgets.QPushButton(self.widget_qrpay)
        self.q_qr_generate.setGeometry(QtCore.QRect(550, 60, 111, 24))
        self.q_qr_generate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_qr_generate.setStyleSheet("QPushButton#q_qr_generate{\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#q_qr_generate:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.q_qr_generate.setObjectName("q_qr_generate")
        self.q_save = QtWidgets.QPushButton(self.widget_qrpay)
        self.q_save.setGeometry(QtCore.QRect(130, 60, 51, 24))
        self.q_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_save.setStyleSheet("QPushButton#q_save{\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#q_save:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.q_save.setObjectName("q_save")
        self.q_clear = QtWidgets.QPushButton(self.widget_qrpay)
        self.q_clear.setGeometry(QtCore.QRect(190, 60, 51, 24))
        self.q_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_clear.setStyleSheet("QPushButton#q_clear{\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#q_clear:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.q_clear.setObjectName("q_clear")
        self.q_qr_widget = QtWidgets.QWidget(self.widget_qrpay)
        self.q_qr_widget.setGeometry(QtCore.QRect(470, 150, 231, 231))
        self.q_qr_widget.setObjectName("q_qr_widget")
        self.q_qr_label = QtWidgets.QLabel(self.q_qr_widget)
        self.q_qr_label.setGeometry(QtCore.QRect(0, -1, 231, 41))
        self.q_qr_label.setStyleSheet("background-color: rgb(45, 55, 69);\n"
"font: 28pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"border-top-right-radius:20px;\n"
"border-bottom-left-radius:20px;")
        self.q_qr_label.setObjectName("q_qr_label")
        self.q_qr_code = QtWidgets.QLabel(self.q_qr_widget)
        self.q_qr_code.setGeometry(QtCore.QRect(30, 50, 171, 151))
        self.q_qr_code.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.q_qr_code.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(63, 81, 181);")
        self.q_qr_code.setObjectName("q_qr_code")
        self.q_c_widget = QtWidgets.QWidget(self.widget_qrpay)
        self.q_c_widget.setGeometry(QtCore.QRect(720, 150, 211, 341))
        self.q_c_widget.setObjectName("q_c_widget")
        self.q_c_seven = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_seven.setGeometry(QtCore.QRect(10, 140, 41, 41))
        self.q_c_seven.setStyleSheet("QPushButton#q_c_seven{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_seven:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_seven:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_seven.setObjectName("q_c_seven")
        self.q_c_eight = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_eight.setGeometry(QtCore.QRect(60, 140, 41, 41))
        self.q_c_eight.setStyleSheet("QPushButton#q_c_eight{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_eight:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_eight:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_eight.setObjectName("q_c_eight")
        self.q_c_nine = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_nine.setGeometry(QtCore.QRect(110, 140, 41, 41))
        self.q_c_nine.setStyleSheet("QPushButton#q_c_nine{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_nine:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_nine:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_nine.setObjectName("q_c_nine")
        self.q_c_four = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_four.setGeometry(QtCore.QRect(10, 190, 41, 41))
        self.q_c_four.setStyleSheet("QPushButton#q_c_four{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_four:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_four:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_four.setObjectName("q_c_four")
        self.q_c_five = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_five.setGeometry(QtCore.QRect(60, 190, 41, 41))
        self.q_c_five.setStyleSheet("QPushButton#q_c_five{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_five:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_five:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_five.setObjectName("q_c_five")
        self.q_c_six = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_six.setGeometry(QtCore.QRect(110, 190, 41, 41))
        self.q_c_six.setStyleSheet("QPushButton#q_c_six{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_six:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_six:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_six.setObjectName("q_c_six")
        self.q_c_one = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_one.setGeometry(QtCore.QRect(10, 240, 41, 41))
        self.q_c_one.setStyleSheet("QPushButton#q_c_one{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_one:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_one:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_one.setObjectName("q_c_one")
        self.q_c_two = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_two.setGeometry(QtCore.QRect(60, 240, 41, 41))
        self.q_c_two.setStyleSheet("QPushButton#q_c_two{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_two:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_two:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_two.setObjectName("q_c_two")
        self.q_c_three = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_three.setGeometry(QtCore.QRect(110, 240, 41, 41))
        self.q_c_three.setStyleSheet("QPushButton#q_c_three{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_three:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_three:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_three.setObjectName("q_c_three")
        self.q_c_zero = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_zero.setGeometry(QtCore.QRect(10, 290, 91, 41))
        self.q_c_zero.setStyleSheet("QPushButton#q_c_zero{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-bottom-left-radius:15px;\n"
"}\n"
"QPushButton#q_c_zero:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_zero:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_zero.setObjectName("q_c_zero")
        self.q_c_dot = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_dot.setGeometry(QtCore.QRect(110, 290, 41, 41))
        self.q_c_dot.setStyleSheet("QPushButton#q_c_dot{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_dot:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_dot:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_dot.setObjectName("q_c_dot")
        self.q_c_c = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_c.setGeometry(QtCore.QRect(10, 90, 41, 41))
        self.q_c_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_c_c.setStyleSheet("QPushButton#q_c_c{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:15px;\n"
"}\n"
"QPushButton#q_c_c:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_c:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_c.setObjectName("q_c_c")
        self.q_c_ac = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_ac.setGeometry(QtCore.QRect(60, 90, 41, 41))
        self.q_c_ac.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_c_ac.setStyleSheet("QPushButton#q_c_ac{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_ac:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_ac:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_ac.setObjectName("q_c_ac")
        self.q_c_div = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_div.setGeometry(QtCore.QRect(110, 90, 41, 41))
        self.q_c_div.setStyleSheet("QPushButton#q_c_div{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton#q_c_div:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_div:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_div.setObjectName("q_c_div")
        self.q_c_mul = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_mul.setGeometry(QtCore.QRect(160, 90, 41, 41))
        self.q_c_mul.setStyleSheet("QPushButton#q_c_mul{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-top-right-radius:15px;\n"
"}\n"
"QPushButton#q_c_mul:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_mul:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_mul.setObjectName("q_c_mul")
        self.q_c_sub = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_sub.setGeometry(QtCore.QRect(160, 140, 41, 41))
        self.q_c_sub.setStyleSheet("QPushButton#q_c_sub{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:0px;\n"
"}\n"
"QPushButton#q_c_sub:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_sub:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_sub.setObjectName("q_c_sub")
        self.q_c_add = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_add.setGeometry(QtCore.QRect(160, 190, 41, 41))
        self.q_c_add.setStyleSheet("QPushButton#q_c_add{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:0px;\n"
"}\n"
"QPushButton#q_c_add:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_add:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_add.setObjectName("q_c_add")
        self.q_c_enter = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_enter.setGeometry(QtCore.QRect(160, 240, 41, 91))
        self.q_c_enter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_c_enter.setStyleSheet("QPushButton#q_c_enter{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(11, 151, 120, 239), stop:0.829545 rgba(85, 98, 112, 226));\n"
"color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:15px;\n"
"}\n"
"QPushButton#q_c_enter:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0, stop:0 rgba(150, 123, 111, 219), stop:0.829545 rgba(85, 81, 84, 226));\n"
"color:rgba(255,255,255,210);\n"
"}\n"
"QPushButton#q_c_enter:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(150,123,111,255)\n"
"}")
        self.q_c_enter.setObjectName("q_c_enter")
        self.q_c_label = QtWidgets.QLabel(self.q_c_widget)
        self.q_c_label.setGeometry(QtCore.QRect(0, 0, 211, 41))
        self.q_c_label.setStyleSheet("background-color: rgb(45, 55, 69);\n"
"font: 28pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.q_c_label.setObjectName("q_c_label")
        self.q_c_display = QtWidgets.QLineEdit(self.q_c_widget)
        self.q_c_display.setGeometry(QtCore.QRect(10, 50, 191, 31))
        self.q_c_display.setStyleSheet("border-radius:15px")
        self.q_c_display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.q_c_display.setReadOnly(True)
        self.q_c_display.setObjectName("q_c_display")
        self.q_c_close = QtWidgets.QPushButton(self.q_c_widget)
        self.q_c_close.setGeometry(QtCore.QRect(0, 0, 41, 24))
        self.q_c_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_c_close.setStyleSheet("background-color: rgb(188, 178, 129);\n"
"color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 9pt \"Segoe Print\";")
        self.q_c_close.setObjectName("q_c_close")
        self.q_p_widget = QtWidgets.QWidget(self.widget_qrpay)
        self.q_p_widget.setGeometry(QtCore.QRect(10, 150, 451, 391))
        self.q_p_widget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.India))
        self.q_p_widget.setObjectName("q_p_widget")
        self.q_p_1pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_1pn.setGeometry(QtCore.QRect(10, 30, 271, 22))
        self.q_p_1pn.setObjectName("q_p_1pn")
        self.q_p_1x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_1x.setGeometry(QtCore.QRect(360, 30, 16, 22))
        self.q_p_1x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_1x.setReadOnly(True)
        self.q_p_1x.setObjectName("q_p_1x")
        self.q_p_label_1 = QtWidgets.QLabel(self.q_p_widget)
        self.q_p_label_1.setGeometry(QtCore.QRect(10, 0, 271, 20))
        self.q_p_label_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 9pt \"Segoe UI\";")
        self.q_p_label_1.setObjectName("q_p_label_1")
        self.q_p_2x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_2x.setGeometry(QtCore.QRect(360, 60, 16, 22))
        self.q_p_2x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_2x.setReadOnly(True)
        self.q_p_2x.setObjectName("q_p_2x")
        self.q_p_2pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_2pn.setGeometry(QtCore.QRect(10, 60, 271, 22))
        self.q_p_2pn.setObjectName("q_p_2pn")
        self.q_p_3x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_3x.setGeometry(QtCore.QRect(360, 90, 16, 22))
        self.q_p_3x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_3x.setReadOnly(True)
        self.q_p_3x.setObjectName("q_p_3x")
        self.q_p_3pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_3pn.setGeometry(QtCore.QRect(10, 90, 271, 22))
        self.q_p_3pn.setObjectName("q_p_3pn")
        self.q_p_4pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_4pn.setGeometry(QtCore.QRect(10, 120, 271, 22))
        self.q_p_4pn.setObjectName("q_p_4pn")
        self.q_p_4x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_4x.setGeometry(QtCore.QRect(360, 120, 16, 22))
        self.q_p_4x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_4x.setReadOnly(True)
        self.q_p_4x.setObjectName("q_p_4x")
        self.q_p_5pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_5pn.setGeometry(QtCore.QRect(10, 150, 271, 22))
        self.q_p_5pn.setObjectName("q_p_5pn")
        self.q_p_5x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_5x.setGeometry(QtCore.QRect(360, 150, 16, 22))
        self.q_p_5x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_5x.setReadOnly(True)
        self.q_p_5x.setObjectName("q_p_5x")
        self.q_p_6pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_6pn.setGeometry(QtCore.QRect(10, 180, 271, 22))
        self.q_p_6pn.setObjectName("q_p_6pn")
        self.q_p_6x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_6x.setGeometry(QtCore.QRect(360, 180, 16, 22))
        self.q_p_6x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_6x.setReadOnly(True)
        self.q_p_6x.setObjectName("q_p_6x")
        self.q_p_7pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_7pn.setGeometry(QtCore.QRect(10, 210, 271, 22))
        self.q_p_7pn.setObjectName("q_p_7pn")
        self.q_p_7x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_7x.setGeometry(QtCore.QRect(360, 210, 16, 22))
        self.q_p_7x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_7x.setReadOnly(True)
        self.q_p_7x.setObjectName("q_p_7x")
        self.q_p_9x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_9x.setGeometry(QtCore.QRect(360, 270, 16, 22))
        self.q_p_9x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_9x.setReadOnly(True)
        self.q_p_9x.setObjectName("q_p_9x")
        self.q_p_12pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_12pn.setGeometry(QtCore.QRect(10, 360, 271, 22))
        self.q_p_12pn.setObjectName("q_p_12pn")
        self.q_p_11x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_11x.setGeometry(QtCore.QRect(360, 330, 16, 22))
        self.q_p_11x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_11x.setReadOnly(True)
        self.q_p_11x.setObjectName("q_p_11x")
        self.q_p_8pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_8pn.setGeometry(QtCore.QRect(10, 240, 271, 22))
        self.q_p_8pn.setObjectName("q_p_8pn")
        self.q_p_10pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_10pn.setGeometry(QtCore.QRect(10, 300, 271, 22))
        self.q_p_10pn.setObjectName("q_p_10pn")
        self.q_p_8x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_8x.setGeometry(QtCore.QRect(360, 240, 16, 22))
        self.q_p_8x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_8x.setReadOnly(True)
        self.q_p_8x.setObjectName("q_p_8x")
        self.q_p_11pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_11pn.setGeometry(QtCore.QRect(10, 330, 271, 22))
        self.q_p_11pn.setObjectName("q_p_11pn")
        self.q_p_12x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_12x.setGeometry(QtCore.QRect(360, 360, 16, 22))
        self.q_p_12x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_12x.setReadOnly(True)
        self.q_p_12x.setObjectName("q_p_12x")
        self.q_p_10x = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_10x.setGeometry(QtCore.QRect(360, 300, 16, 22))
        self.q_p_10x.setAlignment(QtCore.Qt.AlignCenter)
        self.q_p_10x.setReadOnly(True)
        self.q_p_10x.setObjectName("q_p_10x")
        self.q_p_9pn = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_9pn.setGeometry(QtCore.QRect(10, 270, 271, 22))
        self.q_p_9pn.setObjectName("q_p_9pn")
        self.q_p_12p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_12p.setGeometry(QtCore.QRect(290, 360, 61, 22))
        self.q_p_12p.setClearButtonEnabled(True)
        self.q_p_12p.setObjectName("q_p_12p")
        self.q_p_3p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_3p.setGeometry(QtCore.QRect(290, 90, 61, 22))
        self.q_p_3p.setPlaceholderText("")
        self.q_p_3p.setClearButtonEnabled(True)
        self.q_p_3p.setObjectName("q_p_3p")
        self.q_p_5p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_5p.setGeometry(QtCore.QRect(290, 150, 61, 22))
        self.q_p_5p.setPlaceholderText("")
        self.q_p_5p.setClearButtonEnabled(True)
        self.q_p_5p.setObjectName("q_p_5p")
        self.q_p_6p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_6p.setGeometry(QtCore.QRect(290, 180, 61, 22))
        self.q_p_6p.setPlaceholderText("")
        self.q_p_6p.setClearButtonEnabled(True)
        self.q_p_6p.setObjectName("q_p_6p")
        self.q_p_7p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_7p.setGeometry(QtCore.QRect(290, 210, 61, 22))
        self.q_p_7p.setPlaceholderText("")
        self.q_p_7p.setClearButtonEnabled(True)
        self.q_p_7p.setObjectName("q_p_7p")
        self.q_p_9p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_9p.setGeometry(QtCore.QRect(290, 270, 61, 22))
        self.q_p_9p.setClearButtonEnabled(True)
        self.q_p_9p.setObjectName("q_p_9p")
        self.q_p_4p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_4p.setGeometry(QtCore.QRect(290, 120, 61, 22))
        self.q_p_4p.setPlaceholderText("")
        self.q_p_4p.setClearButtonEnabled(True)
        self.q_p_4p.setObjectName("q_p_4p")
        self.q_p_10p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_10p.setGeometry(QtCore.QRect(290, 300, 61, 22))
        self.q_p_10p.setClearButtonEnabled(True)
        self.q_p_10p.setObjectName("q_p_10p")
        self.q_p_2p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_2p.setGeometry(QtCore.QRect(290, 60, 61, 22))
        self.q_p_2p.setPlaceholderText("")
        self.q_p_2p.setClearButtonEnabled(True)
        self.q_p_2p.setObjectName("q_p_2p")
        self.q_p_8p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_8p.setGeometry(QtCore.QRect(290, 240, 61, 22))
        self.q_p_8p.setClearButtonEnabled(True)
        self.q_p_8p.setObjectName("q_p_8p")
        self.q_p_11p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_11p.setGeometry(QtCore.QRect(290, 330, 61, 22))
        self.q_p_11p.setClearButtonEnabled(True)
        self.q_p_11p.setObjectName("q_p_11p")
        self.q_p_1p = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_1p.setGeometry(QtCore.QRect(290, 30, 61, 22))
        self.q_p_1p.setAccessibleDescription("")
        self.q_p_1p.setAutoFillBackground(False)
        self.q_p_1p.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.q_p_1p.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.q_p_1p.setPlaceholderText("")
        self.q_p_1p.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.q_p_1p.setClearButtonEnabled(True)
        self.q_p_1p.setObjectName("q_p_1p")
        self.q_p_label_3 = QtWidgets.QLabel(self.q_p_widget)
        self.q_p_label_3.setGeometry(QtCore.QRect(290, 0, 61, 20))
        self.q_p_label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 9pt \"Segoe UI\";")
        self.q_p_label_3.setObjectName("q_p_label_3")
        self.q_p_label = QtWidgets.QLabel(self.q_p_widget)
        self.q_p_label.setGeometry(QtCore.QRect(0, 0, 441, 21))
        self.q_p_label.setStyleSheet("background-color: rgb(45, 55, 69);\n"
"font: 28pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"border-top-right-radius:15px;\n"
"border-top-left-radius:15px;\n"
"")
        self.q_p_label.setText("")
        self.q_p_label.setObjectName("q_p_label")
        self.q_p_label_2 = QtWidgets.QLabel(self.q_p_widget)
        self.q_p_label_2.setGeometry(QtCore.QRect(390, 0, 49, 21))
        self.q_p_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 9pt \"Segoe UI\";")
        self.q_p_label_2.setObjectName("q_p_label_2")
        self.q_p_12n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_12n.setGeometry(QtCore.QRect(380, 360, 61, 22))
        self.q_p_12n.setClearButtonEnabled(True)
        self.q_p_12n.setObjectName("q_p_12n")
        self.q_p_1n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_1n.setGeometry(QtCore.QRect(380, 30, 61, 22))
        self.q_p_1n.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.q_p_1n.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.q_p_1n.setPlaceholderText("")
        self.q_p_1n.setClearButtonEnabled(True)
        self.q_p_1n.setObjectName("q_p_1n")
        self.q_p_3n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_3n.setGeometry(QtCore.QRect(380, 90, 61, 22))
        self.q_p_3n.setPlaceholderText("")
        self.q_p_3n.setClearButtonEnabled(True)
        self.q_p_3n.setObjectName("q_p_3n")
        self.q_p_5n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_5n.setGeometry(QtCore.QRect(380, 150, 61, 22))
        self.q_p_5n.setPlaceholderText("")
        self.q_p_5n.setClearButtonEnabled(True)
        self.q_p_5n.setObjectName("q_p_5n")
        self.q_p_6n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_6n.setGeometry(QtCore.QRect(380, 180, 61, 22))
        self.q_p_6n.setPlaceholderText("")
        self.q_p_6n.setClearButtonEnabled(True)
        self.q_p_6n.setObjectName("q_p_6n")
        self.q_p_7n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_7n.setGeometry(QtCore.QRect(380, 210, 61, 22))
        self.q_p_7n.setPlaceholderText("")
        self.q_p_7n.setClearButtonEnabled(True)
        self.q_p_7n.setObjectName("q_p_7n")
        self.q_p_9n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_9n.setGeometry(QtCore.QRect(380, 270, 61, 22))
        self.q_p_9n.setClearButtonEnabled(True)
        self.q_p_9n.setObjectName("q_p_9n")
        self.q_p_4n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_4n.setGeometry(QtCore.QRect(380, 120, 61, 22))
        self.q_p_4n.setPlaceholderText("")
        self.q_p_4n.setClearButtonEnabled(True)
        self.q_p_4n.setObjectName("q_p_4n")
        self.q_p_10n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_10n.setGeometry(QtCore.QRect(380, 300, 61, 22))
        self.q_p_10n.setClearButtonEnabled(True)
        self.q_p_10n.setObjectName("q_p_10n")
        self.q_p_2n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_2n.setGeometry(QtCore.QRect(380, 60, 61, 22))
        self.q_p_2n.setPlaceholderText("")
        self.q_p_2n.setClearButtonEnabled(True)
        self.q_p_2n.setObjectName("q_p_2n")
        self.q_p_8n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_8n.setGeometry(QtCore.QRect(380, 240, 61, 22))
        self.q_p_8n.setClearButtonEnabled(True)
        self.q_p_8n.setObjectName("q_p_8n")
        self.q_p_11n = QtWidgets.QLineEdit(self.q_p_widget)
        self.q_p_11n.setGeometry(QtCore.QRect(380, 330, 61, 22))
        self.q_p_11n.setClearButtonEnabled(True)
        self.q_p_11n.setObjectName("q_p_11n")
        self.q_p_label.raise_()
        self.q_p_1pn.raise_()
        self.q_p_1x.raise_()
        self.q_p_label_1.raise_()
        self.q_p_2x.raise_()
        self.q_p_2pn.raise_()
        self.q_p_3x.raise_()
        self.q_p_3pn.raise_()
        self.q_p_4pn.raise_()
        self.q_p_4x.raise_()
        self.q_p_5pn.raise_()
        self.q_p_5x.raise_()
        self.q_p_6pn.raise_()
        self.q_p_6x.raise_()
        self.q_p_7pn.raise_()
        self.q_p_7x.raise_()
        self.q_p_9x.raise_()
        self.q_p_12pn.raise_()
        self.q_p_11x.raise_()
        self.q_p_8pn.raise_()
        self.q_p_10pn.raise_()
        self.q_p_8x.raise_()
        self.q_p_11pn.raise_()
        self.q_p_12x.raise_()
        self.q_p_10x.raise_()
        self.q_p_9pn.raise_()
        self.q_p_12p.raise_()
        self.q_p_3p.raise_()
        self.q_p_5p.raise_()
        self.q_p_6p.raise_()
        self.q_p_7p.raise_()
        self.q_p_9p.raise_()
        self.q_p_4p.raise_()
        self.q_p_10p.raise_()
        self.q_p_2p.raise_()
        self.q_p_8p.raise_()
        self.q_p_11p.raise_()
        self.q_p_1p.raise_()
        self.q_p_label_3.raise_()
        self.q_p_label_2.raise_()
        self.q_p_12n.raise_()
        self.q_p_1n.raise_()
        self.q_p_3n.raise_()
        self.q_p_5n.raise_()
        self.q_p_6n.raise_()
        self.q_p_7n.raise_()
        self.q_p_9n.raise_()
        self.q_p_4n.raise_()
        self.q_p_10n.raise_()
        self.q_p_2n.raise_()
        self.q_p_8n.raise_()
        self.q_p_11n.raise_()
        self.q_c = QtWidgets.QPushButton(self.widget_qrpay)
        self.q_c.setGeometry(QtCore.QRect(830, 110, 71, 24))
        self.q_c.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_c.setObjectName("q_c")
        self.pushButton = QtWidgets.QPushButton(self.widget_qrpay)
        self.pushButton.setGeometry(QtCore.QRect(460, 110, 75, 24))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.q_reference = QtWidgets.QLineEdit(self.widget_qrpay)
        self.q_reference.setGeometry(QtCore.QRect(640, 110, 181, 22))
        self.q_reference.setClearButtonEnabled(True)
        self.q_reference.setObjectName("q_reference")
        self.q_payment = QtWidgets.QComboBox(self.widget_qrpay)
        self.q_payment.setGeometry(QtCore.QRect(540, 110, 91, 22))
        self.q_payment.setObjectName("q_payment")
        self.q_payment.addItem("")
        self.q_payment.addItem("")
        self.q_payment.addItem("")
        self.q_widget_profile = QtWidgets.QWidget(self.widget_qrpay)
        self.q_widget_profile.setGeometry(QtCore.QRect(140, 10, 661, 541))
        self.q_widget_profile.setObjectName("q_widget_profile")
        self.profile_label_2 = QtWidgets.QLabel(self.q_widget_profile)
        self.profile_label_2.setGeometry(QtCore.QRect(0, 0, 661, 41))
        self.profile_label_2.setStyleSheet("background-color: rgb(145, 60, 70);\n"
"font: 28pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-right-radius:40px;\n"
"border-bottom-left-radius:40px;")
        self.profile_label_2.setObjectName("profile_label_2")
        self.q_profile_close_2 = QtWidgets.QPushButton(self.q_widget_profile)
        self.q_profile_close_2.setGeometry(QtCore.QRect(0, 0, 51, 41))
        self.q_profile_close_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.q_profile_close_2.setStyleSheet("background-color: rgb(188, 178, 129);\n"
"font: 10pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-left-radius:40px;")
        self.q_profile_close_2.setObjectName("q_profile_close_2")
        self.profile_shop_name = QtWidgets.QLineEdit(self.q_widget_profile)
        self.profile_shop_name.setGeometry(QtCore.QRect(50, 160, 561, 22))
        self.profile_shop_name.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 11pt \"Lucida Calligraphy\";\n"
"color: rgb(2, 10, 91);")
        self.profile_shop_name.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_shop_name.setReadOnly(True)
        self.profile_shop_name.setObjectName("profile_shop_name")
        self.profile_shop_wo_name = QtWidgets.QLineEdit(self.q_widget_profile)
        self.profile_shop_wo_name.setGeometry(QtCore.QRect(50, 250, 281, 22))
        self.profile_shop_wo_name.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 11pt \"Lucida Calligraphy\";\n"
"color: rgb(2, 10, 91);")
        self.profile_shop_wo_name.setReadOnly(True)
        self.profile_shop_wo_name.setObjectName("profile_shop_wo_name")
        self.label_27 = QtWidgets.QLabel(self.q_widget_profile)
        self.label_27.setGeometry(QtCore.QRect(50, 210, 61, 41))
        self.label_27.setStyleSheet("font: 11pt \"Segoe Print\";\n"
"color: rgb(144, 51, 61);")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.q_widget_profile)
        self.label_28.setGeometry(QtCore.QRect(350, 210, 151, 41))
        self.label_28.setStyleSheet("font: 11pt \"Segoe Print\";\n"
"color: rgb(144, 51, 61);")
        self.label_28.setObjectName("label_28")
        self.profile_shop_phone = QtWidgets.QLineEdit(self.q_widget_profile)
        self.profile_shop_phone.setGeometry(QtCore.QRect(350, 250, 261, 22))
        self.profile_shop_phone.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 11pt \"Lucida Calligraphy\";\n"
"color: rgb(2, 10, 91);")
        self.profile_shop_phone.setReadOnly(True)
        self.profile_shop_phone.setObjectName("profile_shop_phone")
        self.label_29 = QtWidgets.QLabel(self.q_widget_profile)
        self.label_29.setGeometry(QtCore.QRect(50, 280, 41, 41))
        self.label_29.setStyleSheet("\n"
"font: 700 11pt \"Segoe Print\";\n"
"color: rgb(144, 51, 61);")
        self.label_29.setObjectName("label_29")
        self.profile_shop_upi = QtWidgets.QLineEdit(self.q_widget_profile)
        self.profile_shop_upi.setGeometry(QtCore.QRect(50, 320, 191, 22))
        self.profile_shop_upi.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 11pt \"Lucida Calligraphy\";\n"
"color: rgb(2, 10, 91);")
        self.profile_shop_upi.setReadOnly(True)
        self.profile_shop_upi.setObjectName("profile_shop_upi")
        self.label_30 = QtWidgets.QLabel(self.q_widget_profile)
        self.label_30.setGeometry(QtCore.QRect(260, 280, 71, 41))
        self.label_30.setStyleSheet("font: 11pt \"Segoe Print\";\n"
"color: rgb(144, 51, 61);")
        self.label_30.setObjectName("label_30")
        self.profile_shop_email = QtWidgets.QLineEdit(self.q_widget_profile)
        self.profile_shop_email.setGeometry(QtCore.QRect(260, 320, 281, 22))
        self.profile_shop_email.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"font: 11pt \"Lucida Calligraphy\";\n"
"color: rgb(2, 10, 91);")
        self.profile_shop_email.setReadOnly(True)
        self.profile_shop_email.setObjectName("profile_shop_email")
        self.profile_update = QtWidgets.QPushButton(self.q_widget_profile)
        self.profile_update.setGeometry(QtCore.QRect(120, 390, 75, 24))
        self.profile_update.setStyleSheet("QPushButton#profile_update{\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#profile_update:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.profile_update.setObjectName("profile_update")
        self.profile_save = QtWidgets.QPushButton(self.q_widget_profile)
        self.profile_save.setGeometry(QtCore.QRect(290, 390, 75, 24))
        self.profile_save.setStyleSheet("QPushButton#profile_save{\n"
"border-radius:10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0.0113636, x2:0.5, y2:1, stop:0 rgba(255, 255, 127, 255), stop:0.829545 rgba(255, 186, 186, 255));\n"
"}\n"
"QPushButton#profile_save:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}")
        self.profile_save.setObjectName("profile_save")
        self.widget_history = QtWidgets.QWidget(self.widget_qrpay)
        self.widget_history.setGeometry(QtCore.QRect(20, 10, 901, 531))
        self.widget_history.setObjectName("widget_history")
        self.history_tableWidget = QtWidgets.QTableWidget(self.widget_history)
        self.history_tableWidget.setGeometry(QtCore.QRect(10, 90, 881, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_tableWidget.sizePolicy().hasHeightForWidth())
        self.history_tableWidget.setSizePolicy(sizePolicy)
        self.history_tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.history_tableWidget.setMaximumSize(QtCore.QSize(921, 16777215))
        self.history_tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.history_tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.history_tableWidget.setMouseTracking(False)
        self.history_tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(141, 206, 198);\n"
"font: 12pt \"Arial\";\n"
"")
        self.history_tableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.India))
        self.history_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.history_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.history_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.history_tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.history_tableWidget.setObjectName("history_tableWidget")
        self.history_tableWidget.setColumnCount(7)
        self.history_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.history_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.history_tableWidget.setHorizontalHeaderItem(6, item)
        self.history_tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.history_search = QtWidgets.QPushButton(self.widget_history)
        self.history_search.setGeometry(QtCore.QRect(430, 40, 81, 31))
        self.history_search.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 12pt \"Segoe Script\";")
        self.history_search.setObjectName("history_search")
        self.history_label = QtWidgets.QLabel(self.widget_history)
        self.history_label.setGeometry(QtCore.QRect(310, 0, 331, 31))
        self.history_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:0.29, x2:0.533292, y2:0.676, stop:0 rgba(0, 135, 135, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.history_label.setObjectName("history_label")
        self.history_close = QtWidgets.QPushButton(self.widget_history)
        self.history_close.setGeometry(QtCore.QRect(260, 0, 51, 31))
        self.history_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_close.setStyleSheet("background-color: rgb(188, 178, 129);\n"
"font: 10pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-left-radius:29px;")
        self.history_close.setObjectName("history_close")
        self.widget_search = QtWidgets.QWidget(self.widget_qrpay)
        self.widget_search.setGeometry(QtCore.QRect(30, 0, 901, 421))
        self.widget_search.setObjectName("widget_search")
        self.search_tableWidget = QtWidgets.QTableWidget(self.widget_search)
        self.search_tableWidget.setGeometry(QtCore.QRect(10, 100, 861, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_tableWidget.sizePolicy().hasHeightForWidth())
        self.search_tableWidget.setSizePolicy(sizePolicy)
        self.search_tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.search_tableWidget.setMaximumSize(QtCore.QSize(921, 16777215))
        self.search_tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.search_tableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.search_tableWidget.setMouseTracking(False)
        self.search_tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(141, 206, 198);\n"
"font: 12pt \"Arial\";\n"
"")
        self.search_tableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.India))
        self.search_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.search_tableWidget.setDragDropOverwriteMode(True)
        self.search_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.search_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.search_tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.search_tableWidget.setObjectName("search_tableWidget")
        self.search_tableWidget.setColumnCount(7)
        self.search_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.search_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_tableWidget.setHorizontalHeaderItem(6, item)
        self.search_tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.search_label = QtWidgets.QLabel(self.widget_search)
        self.search_label.setGeometry(QtCore.QRect(300, 10, 331, 31))
        self.search_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:0.29, x2:0.533292, y2:0.676, stop:0 rgba(0, 135, 135, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.search_label.setObjectName("search_label")
        self.search_name = QtWidgets.QLineEdit(self.widget_search)
        self.search_name.setGeometry(QtCore.QRect(280, 60, 371, 31))
        self.search_name.setStyleSheet("color: rgb(0, 0, 70);\n"
"font: 700 14pt \"Segoe UI Variable Display\";")
        self.search_name.setObjectName("search_name")
        self.search_label_2 = QtWidgets.QLabel(self.widget_search)
        self.search_label_2.setGeometry(QtCore.QRect(80, 60, 171, 31))
        self.search_label_2.setStyleSheet("color: rgb(220, 127, 127);\n"
"font: 700 15pt \"Segoe Print\";")
        self.search_label_2.setObjectName("search_label_2")
        self.search_close = QtWidgets.QPushButton(self.widget_search)
        self.search_close.setGeometry(QtCore.QRect(250, 10, 51, 31))
        self.search_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_close.setStyleSheet("background-color: rgb(188, 178, 129);\n"
"font: 10pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-left-radius:29px;")
        self.search_close.setObjectName("search_close")
        self.search_search = QtWidgets.QPushButton(self.widget_search)
        self.search_search.setGeometry(QtCore.QRect(670, 60, 75, 31))
        self.search_search.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 700 12pt \"Segoe Script\";")
        self.search_search.setObjectName("search_search")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QrPay"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "©2021 Dibyataru_Chakraborty"))
        self.s_register.setText(_translate("Form", "Sign Up"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700; font-style:italic;\">Sign Up</span></p></body></html>"))
        self.s_email.setPlaceholderText(_translate("Form", "Email"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Password</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Confirm Password</span></p></body></html>"))
        self.s_password.setPlaceholderText(_translate("Form", "Password"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Email</span></p></body></html>"))
        self.s_confirm_password.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.s_back.setText(_translate("Form", "<"))
        self.l_password.setPlaceholderText(_translate("Form", "Password"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Email</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Password</span></p></body></html>"))
        self.l_forget.setText(_translate("Form", "Forget Password?"))
        self.l_login.setText(_translate("Form", "Log In"))
        self.l_email.setPlaceholderText(_translate("Form", "Email"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700; font-style:italic;\">Log in</span></p></body></html>"))
        self.l_back.setText(_translate("Form", "<"))
        self.f_otp.setPlaceholderText(_translate("Form", "otp"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700; font-style:italic;\">Forgot Password</span></p></body></html>"))
        self.f_resend.setText(_translate("Form", "Resend"))
        self.f_submit.setText(_translate("Form", "Submit"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">OTP</span></p></body></html>"))
        self.f_back.setText(_translate("Form", "<"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-style:italic;\">Welcome</span></p></body></html>"))
        self.w_login.setText(_translate("Form", "Log In"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Sign or Create a new Account</span></p></body></html>"))
        self.w_register.setText(_translate("Form", "Create a new Account"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700; font-style:italic;\">Register Your Details</span></p></body></html>"))
        self.r_register.setText(_translate("Form", "Register"))
        self.r_last_name.setPlaceholderText(_translate("Form", "Shop Name"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Shop Name</span></p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Name</span></p></body></html>"))
        self.label_19.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Password</span></p></body></html>"))
        self.r_upi.setPlaceholderText(_translate("Form", "UPI"))
        self.r_answer.setPlaceholderText(_translate("Form", "Answer"))
        self.r_comboBox.setItemText(0, _translate("Form", "Select"))
        self.r_comboBox.setItemText(1, _translate("Form", "Birth Place"))
        self.r_comboBox.setItemText(2, _translate("Form", "Favourit Book"))
        self.r_comboBox.setItemText(3, _translate("Form", "Favourit Place"))
        self.r_first_name.setPlaceholderText(_translate("Form", "Name"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Phone Number</span></p></body></html>"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">UPI Id</span></p></body></html>"))
        self.label_22.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Security Question</span></p></body></html>"))
        self.r_phone_number.setPlaceholderText(_translate("Form", "Phone Number"))
        self.label_23.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Email</span></p></body></html>"))
        self.label_24.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Answer</span></p></body></html>"))
        self.r_back.setText(_translate("Form", "<"))
        self.q_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:700; font-style:italic; text-decoration: underline;\">QrPay</span></p></body></html>"))
        self.q_acc_ount.setText(_translate("Form", "Account"))
        self.q_log_out.setText(_translate("Form", "Log Out"))
        self.q_old_details.setText(_translate("Form", "Old Details"))
        self.q_customer_name.setPlaceholderText(_translate("Form", "Customer Name"))
        self.q_amount.setPlaceholderText(_translate("Form", "Amount"))
        self.q_customer_Phone.setPlaceholderText(_translate("Form", "Customer Phone"))
        self.q_upi.setPlaceholderText(_translate("Form", "UPI ID"))
        self.q_qr_generate.setText(_translate("Form", "Qr Code Generate"))
        self.q_save.setText(_translate("Form", "Save"))
        self.q_clear.setText(_translate("Form", "Clear"))
        self.q_qr_label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Qr Code</p></body></html>"))
        self.q_qr_code.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:700; font-style:italic;\">No Qr Available</span></p></body></html>"))
        self.q_c_seven.setText(_translate("Form", "7"))
        self.q_c_eight.setText(_translate("Form", "8"))
        self.q_c_nine.setText(_translate("Form", "9"))
        self.q_c_four.setText(_translate("Form", "4"))
        self.q_c_five.setText(_translate("Form", "5"))
        self.q_c_six.setText(_translate("Form", "6"))
        self.q_c_one.setText(_translate("Form", "1"))
        self.q_c_two.setText(_translate("Form", "2"))
        self.q_c_three.setText(_translate("Form", "3"))
        self.q_c_zero.setText(_translate("Form", "0"))
        self.q_c_dot.setText(_translate("Form", "."))
        self.q_c_c.setText(_translate("Form", "C"))
        self.q_c_ac.setText(_translate("Form", "AC"))
        self.q_c_div.setText(_translate("Form", "/"))
        self.q_c_mul.setText(_translate("Form", "*"))
        self.q_c_sub.setText(_translate("Form", "-"))
        self.q_c_add.setText(_translate("Form", "+"))
        self.q_c_enter.setText(_translate("Form", "Enter"))
        self.q_c_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-style:italic;\">Calculator</span></p></body></html>"))
        self.q_c_display.setPlaceholderText(_translate("Form", "0"))
        self.q_c_close.setText(_translate("Form", "Close"))
        self.q_p_1pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_1x.setText(_translate("Form", "x"))
        self.q_p_label_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">Product name</span></p></body></html>"))
        self.q_p_2x.setText(_translate("Form", "x"))
        self.q_p_2pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_3x.setText(_translate("Form", "x"))
        self.q_p_3pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_4pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_4x.setText(_translate("Form", "x"))
        self.q_p_5pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_5x.setText(_translate("Form", "x"))
        self.q_p_6pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_6x.setText(_translate("Form", "x"))
        self.q_p_7pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_7x.setText(_translate("Form", "x"))
        self.q_p_9x.setText(_translate("Form", "x"))
        self.q_p_12pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_11x.setText(_translate("Form", "x"))
        self.q_p_8pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_10pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_8x.setText(_translate("Form", "x"))
        self.q_p_11pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_12x.setText(_translate("Form", "x"))
        self.q_p_10x.setText(_translate("Form", "x"))
        self.q_p_9pn.setPlaceholderText(_translate("Form", "Product Name"))
        self.q_p_12p.setText(_translate("Form", "0"))
        self.q_p_3p.setText(_translate("Form", "0"))
        self.q_p_5p.setText(_translate("Form", "0"))
        self.q_p_6p.setText(_translate("Form", "0"))
        self.q_p_7p.setText(_translate("Form", "0"))
        self.q_p_9p.setText(_translate("Form", "0"))
        self.q_p_4p.setText(_translate("Form", "0"))
        self.q_p_10p.setText(_translate("Form", "0"))
        self.q_p_2p.setText(_translate("Form", "0"))
        self.q_p_8p.setText(_translate("Form", "0"))
        self.q_p_11p.setText(_translate("Form", "0"))
        self.q_p_1p.setText(_translate("Form", "0"))
        self.q_p_label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">Price</span></p></body></html>"))
        self.q_p_label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:700;\">No.</span></p></body></html>"))
        self.q_p_12n.setText(_translate("Form", "0"))
        self.q_p_1n.setText(_translate("Form", "0"))
        self.q_p_3n.setText(_translate("Form", "0"))
        self.q_p_5n.setText(_translate("Form", "0"))
        self.q_p_6n.setText(_translate("Form", "0"))
        self.q_p_7n.setText(_translate("Form", "0"))
        self.q_p_9n.setText(_translate("Form", "0"))
        self.q_p_4n.setText(_translate("Form", "0"))
        self.q_p_10n.setText(_translate("Form", "0"))
        self.q_p_2n.setText(_translate("Form", "0"))
        self.q_p_8n.setText(_translate("Form", "0"))
        self.q_p_11n.setText(_translate("Form", "0"))
        self.q_c.setText(_translate("Form", "Calculator"))
        self.pushButton.setText(_translate("Form", "Total"))
        self.q_reference.setPlaceholderText(_translate("Form", "Reference  No."))
        self.q_payment.setItemText(0, _translate("Form", "Select"))
        self.q_payment.setItemText(1, _translate("Form", "Paid"))
        self.q_payment.setItemText(2, _translate("Form", "Due"))
        self.profile_label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:700; font-style:italic; text-decoration: underline;\">Profile</span></p></body></html>"))
        self.q_profile_close_2.setText(_translate("Form", "Close"))
        self.label_27.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic;\">Name</span></p></body></html>"))
        self.label_28.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic;\">Phone Number</span></p></body></html>"))
        self.label_29.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">UPI</span></p></body></html>"))
        self.label_30.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic;\">EMAIL</span></p></body></html>"))
        self.profile_update.setText(_translate("Form", "Update"))
        self.profile_save.setText(_translate("Form", "Save"))
        self.history_tableWidget.setSortingEnabled(True)
        item = self.history_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Amount"))
        item = self.history_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Customer Name"))
        item = self.history_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Customer Phone"))
        item = self.history_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Date"))
        item = self.history_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Payment Status"))
        item = self.history_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Reference No"))
        item = self.history_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "UPI ID"))
        self.history_search.setText(_translate("Form", "Search"))
        self.history_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Payment Details</span></p></body></html>"))
        self.history_close.setText(_translate("Form", "Close"))
        self.search_tableWidget.setSortingEnabled(True)
        item = self.search_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Amount"))
        item = self.search_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Customer Name"))
        item = self.search_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Customer Phone"))
        item = self.search_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Date"))
        item = self.search_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Payment Status"))
        item = self.search_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Reference No"))
        item = self.search_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "UPI ID"))
        self.search_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Search By Name</span></p></body></html>"))
        self.search_label_2.setText(_translate("Form", "Customer Name"))
        self.search_close.setText(_translate("Form", "Close"))
        self.search_search.setText(_translate("Form", "Search"))
import image
